// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class FilterOptions {
  final bool isWithParts;
  final int from;
  final int to;

  const FilterOptions({
    required this.isWithParts,
    required this.from,
    required this.to,
  });

  @override
  int get hashCode => isWithParts.hashCode ^ from.hashCode ^ to.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FilterOptions &&
          runtimeType == other.runtimeType &&
          isWithParts == other.isWithParts &&
          from == other.from &&
          to == other.to;
}
