// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

class BasicInfo {
  final String id;
  final String title;
  final String coverUrl;
  final String author;
  final PlatformInt64 count;
  final String tname;
  final String pubdate;
  final String desc;

  const BasicInfo({
    required this.id,
    required this.title,
    required this.coverUrl,
    required this.author,
    required this.count,
    required this.tname,
    required this.pubdate,
    required this.desc,
  });

  static Future<BasicInfo> fromCollection({required Collection collect}) =>
      RustLib.instance.api.crateApiModulesBasicInfoFromCollection(
        collect: collect,
      );

  static Future<BasicInfo> fromVideo({required Video video}) =>
      RustLib.instance.api.crateApiModulesBasicInfoFromVideo(video: video);

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      coverUrl.hashCode ^
      author.hashCode ^
      count.hashCode ^
      tname.hashCode ^
      pubdate.hashCode ^
      desc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BasicInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          coverUrl == other.coverUrl &&
          author == other.author &&
          count == other.count &&
          tname == other.tname &&
          pubdate == other.pubdate &&
          desc == other.desc;
}
